import './globals.css';
import { Suspense } from 'react';
import Script from 'next/script';
import dynamic from 'next/dynamic';
import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import { ThemeProvider } from './provider';
import { NextAuthProvider } from '@/providers';
import { NavBar, OffCanvas, Footer } from '@/components';

const HeaderDynamic = dynamic(() => import('@/components/header'), {
  loading: () => <p>Loading...</p>,
  ssr: true,
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className + ' bg-white dark:bg-black'}>
        <ThemeProvider>
          <NextAuthProvider>
            <div className={'flex flex-col justify-between min-h-screen'}>
              <HeaderDynamic />
              <NavBar />
              <OffCanvas />
              {children}
              <Footer />
            </div>
            <Script src="./node_modules/preline/dist/preline.js" />
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
