import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ThemeProvider } from '@/context';
import DynamicScriptComponent from './lib';
import { NextAuthProvider } from '@/providers';
import { Header, NavBar, OffCanvas, Footer } from '@/components';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <NextAuthProvider>
            <Header />
            <NavBar />
            <OffCanvas />
            {children}
            <Footer />
            <DynamicScriptComponent />
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
