import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import DynamicScriptComponent from './lib'
import Footer from './components/footer'
import Header from './components/header'
import Offcanvas from './components/offcanvas'
import Navbar from './components/navbar'

import { NextAuthProvider } from '@/providers'
import { ThemeProvider } from '@/context'
        
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <NextAuthProvider>
            <Header />
            <Navbar />
            <Offcanvas />
               {children}        
            <Footer />
            <DynamicScriptComponent />
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}